My Project: src/commons/config.h File Reference
config.h File Reference
#include <commons/config.h>
#include "collections/dictionary.h"
Data Structures
struct t_config
Manejo de archivos de configuración. Inicializar con config_create().
Functions
t_config * config_create (char *path)
Crea una estructura t_config.
bool config_has_property (t_config *, char *key)
Retorna true si key se encuentra en la configuracion.
char * config_get_string_value (t_config *, char *key)
Retorna un string con el valor asociado a key.
int config_get_int_value (t_config *, char *key)
Retorna un int con el valor asociado a key.
long config_get_long_value (t_config *, char *key)
Retorna un long con el valor asociado a key.
double config_get_double_value (t_config *, char *key)
Retorna un double con el valor asociado a key.
char ** config_get_array_value (t_config *, char *key)
Retorna un array con los valores asociados a la key especificada.
int config_keys_amount (t_config *)
Retorna la cantidad de keys.
void config_destroy (t_config *config)
Destruye la estructura config.
void config_set_value (t_config *, char *key, char *value)
Setea el valor en el archivo de config, a la key asociada.
void config_remove_key (t_config *, char *key)
Remueve la clave y su valor asociado del archivo de config.
int config_save (t_config *)
Reescribe el archivo de configuracion con los valores del config.
int config_save_in_file (t_config *, char *path)
Escribe un archivo de configuracion en el path indicado con los valores del config.
Detailed Description
#include <commons/config.h>
Definition in file config.h.
Function Documentation
config_create()
t_config* config_create (char * path)
Crea una estructura t_config.
Parameters
path Ruta hacia el archivo de configuracion
Returns
Retorna un puntero hacia la estructura creada, o NULL en caso de no encontrar el archivo en el path especificado. Una vez que se deje de usar, se debe liberar con config_destroy().
Definition at line 26 of file config.c.
References dictionary_create(), dictionary_put(), string_array_destroy(), string_is_empty(), string_iterate_lines(), string_n_split(), string_split(), string_starts_with(), and string_trim().
config_get_array_value()
char** config_get_array_value (t_config * , char * key)
Retorna un array con los valores asociados a la key especificada.
Returns
Devuelve un array de strings terminado en NULL. Debe ser liberado con string_array_destroy() una vez que se deje de usar.
Note
En el archivo de configuracion un valor de este tipo debería ser representado de la siguiente forma [lista_valores_separados_por_coma]. Ejemplo:
VALORES=[1,2,3,4,5]
Definition at line 95 of file config.c.
References config_get_string_value(), and string_get_string_as_array().
config_get_string_value()
char* config_get_string_value (t_config * , char * key)
Retorna un string con el valor asociado a key.
Warning
Devuelve un puntero perteneciente a la estructura t_config, por lo que no debe ser liberado por fuera de la misma.
Definition at line 76 of file config.c.
References dictionary_get().
config_save()
int config_save (t_config *)
Reescribe el archivo de configuracion con los valores del config.
Returns
Retorna mayor a 0 si se pudo guardar el archivo, -1 en caso de error.
Definition at line 126 of file config.c.
References config_save_in_file().
config_save_in_file()
int config_save_in_file (t_config * , char * path)
Escribe un archivo de configuracion en el path indicado con los valores del config.
Returns
Retorna mayor a 0 si se pudo guardar el archivo, -1 en caso de error.
Definition at line 130 of file config.c.
References dictionary_iterator(), string_append_with_format(), and string_new().