My Project: src/commons/log.h File Reference
log.h File Reference
#include <commons/log.h>
#include <stdio.h>
#include <stdbool.h>
#include <sys/types.h>
Data Structures
struct t_log
Manejo de logs. Inicializar con log_create()
Enumerations
enum t_log_level {
LOG_LEVEL_TRACE, LOG_LEVEL_DEBUG, LOG_LEVEL_INFO, LOG_LEVEL_WARNING,
LOG_LEVEL_ERROR
}
Functions
t_log * log_create (char *file, char *process_name, bool is_active_console, t_log_level level)
Crea una instancia de logger.
void log_destroy (t_log *logger)
Destruye una instancia de logger.
void log_trace (t_log *logger, const char *message,...) __attribute__((format(printf
Loguea un mensaje con el siguiente formato [TRACE] hh:mm:ss:mmmm PROCESS_NAME/(PID:TID): MESSAGE
void void log_debug (t_log *logger, const char *message,...) __attribute__((format(printf
Loguea un mensaje con el siguiente formato [DEBUG] hh:mm:ss:mmmm PROCESS_NAME/(PID:TID): MESSAGE
void void void log_info (t_log *logger, const char *message,...) __attribute__((format(printf
Loguea un mensaje con el siguiente formato [INFO] hh:mm:ss:mmmm PROCESS_NAME/(PID:TID): MESSAGE
void void void void log_warning (t_log *logger, const char *message,...) __attribute__((format(printf
Loguea un mensaje con el siguiente formato [WARNING] hh:mm:ss:mmmm PROCESS_NAME/(PID:TID): MESSAGE
void void void void void log_error (t_log *logger, const char *message,...) __attribute__((format(printf
Loguea un mensaje con el siguiente formato [ERROR] hh:mm:ss:mmmm PROCESS_NAME/(PID:TID): MESSAGE
void void void void void char * log_level_as_string (t_log_level level)
Convierte un t_log_level a su representacion en string.
t_log_level log_level_from_string (char *level)
Convierte un string a su representacion en t_log_level.
Detailed Description
#include <commons/log.h>
Definition in file log.h.
Enumeration Type Documentation
t_log_level
enum t_log_level
Enumerator
LOG_LEVEL_TRACE
Loguea todos los mensajes.
LOG_LEVEL_DEBUG
Loguea solo mensajes de log_debug en adelante.
LOG_LEVEL_INFO
Loguea solo mensajes de log_info en adelante.
LOG_LEVEL_WARNING
Loguea solo mensajes de log_warning en adelante.
LOG_LEVEL_ERROR
Loguea solo mensajes de log_error.
Definition at line 28 of file log.h.
Function Documentation
log_create()
t_log* log_create (char * file, char * program_name, bool is_active_console, t_log_level detail)
Crea una instancia de logger.
Parameters
file La ruta hacia el archivo donde se van a generar los logs, debe tener extensión .log
process_name El nombre a ser mostrado en los logs
is_active_console Si lo que se loguea debe mostrarse por consola
level El nivel de detalle máximo a loguear (ver definición de t_log_level)
Returns
Retorna una instancia de logger, o NULL en caso de error. Debe ser liberada con log_destroy()
Note
Se debe tener en cuenta que:
si file ya existe, se escribirá al final del archivo
si file no existe, se creará un nuevo archivo en el directorio indicado
si el directorio hacia file no existe, se producirá un error
si file es NULL, no se escribirá en ningún archivo
Public Functions
Definition at line 46 of file log.c.
References error_show(), process_getpid(), string_duplicate(), string_ends_with(), and txt_open_for_append().
log_debug()
void void log_debug (t_log * logger, const char * message, ...)
Loguea un mensaje con el siguiente formato [DEBUG] hh:mm:ss:mmmm PROCESS_NAME/(PID:TID): MESSAGE
log_error()
void void void void void log_error (t_log * logger, const char * message, ...)
Loguea un mensaje con el siguiente formato [ERROR] hh:mm:ss:mmmm PROCESS_NAME/(PID:TID): MESSAGE
log_info()
void void void log_info (t_log * logger, const char * message, ...)
Loguea un mensaje con el siguiente formato [INFO] hh:mm:ss:mmmm PROCESS_NAME/(PID:TID): MESSAGE
log_level_as_string()
void void void void void char* log_level_as_string (t_log_level level)
Convierte un t_log_level a su representacion en string.
Parameters
level El nivel de log a convertir
Returns
"TRACE", "DEBUG", "INFO", "WARNING" o "ERROR"
Definition at line 120 of file log.c.
log_level_from_string()
t_log_level log_level_from_string (char * level)
Convierte un string a su representacion en t_log_level.
Parameters
level "TRACE", "DEBUG", "INFO", "WARNING" o "ERROR"
Returns
El nivel de log correspondiente, o -1 en caso de no ser un nivel de log válido
Definition at line 128 of file log.c.
References string_equals_ignore_case().
log_trace()
void log_trace (t_log * logger, const char * message, ...)
Loguea un mensaje con el siguiente formato [TRACE] hh:mm:ss:mmmm PROCESS_NAME/(PID:TID): MESSAGE
log_warning()
void void void void log_warning (t_log * logger, const char * message, ...)
Loguea un mensaje con el siguiente formato [WARNING] hh:mm:ss:mmmm PROCESS_NAME/(PID:TID): MESSAGE