My Project: src/commons/collections/queue.h File Reference
queue.h File Reference
#include <commons/collections/queue.h>
#include "list.h"
Data Structures
struct t_queue
Estructura que representa una cola. Inicializar con queue_create()
Functions
t_queue * queue_create (void)
Crea una cola.
void queue_destroy (t_queue *)
Destruye una cola sin liberar los elementos que contiene.
void queue_destroy_and_destroy_elements (t_queue *, void(*element_destroyer)(void *))
Destruye una cola, recibiendo como argumento el metodo encargado de liberar cada elemento de la cola.
void queue_push (t_queue *, void *element)
Agrega un elemento al final de la cola.
void * queue_pop (t_queue *)
quita el primer elemento de la cola
void * queue_peek (t_queue *)
Devuelve el primer elemento de la cola sin extraerlo.
void queue_clean (t_queue *)
Quita todos los elementos de la cola sin liberarlos.
void queue_clean_and_destroy_elements (t_queue *, void(*element_destroyer)(void *))
Quita y libera todos los elementos de la cola.
int queue_size (t_queue *)
Devuelve la cantidad de elementos de la cola.
bool queue_is_empty (t_queue *)
Verifica si la cola esta vacía.
Detailed Description
#include <commons/collections/queue.h>
Definition in file queue.h.
Function Documentation
queue_create()
t_queue* queue_create (void)
Crea una cola.
Returns
Retorna un puntero a la cola creada, liberable con:
queue_destroy() si se quiere liberar la cola pero no los elementos que contiene.
queue_destroy_and_destroy_elements() si se quiere liberar la cola con los elementos que contiene.
Definition at line 21 of file queue.c.
References list_create().
queue_peek()
void* queue_peek (t_queue *)
Devuelve el primer elemento de la cola sin extraerlo.
Returns
El primer elemento de la cola. Este elemento no debe ser liberado ya que seguirá perteneciendo a la cola.
Definition at line 54 of file queue.c.
References list_get().
queue_pop()
void* queue_pop (t_queue *)
quita el primer elemento de la cola
Returns
El elemento extraído de la cola. Este elemento debe ser liberado una vez que se deje de usar.
Definition at line 50 of file queue.c.
References list_remove().
queue_push()
void queue_push (t_queue * , void * element)
Agrega un elemento al final de la cola.
Parameters
element Elemento a agregar. Este elemento pasará a pertenecer a la cola, por lo que no debe ser liberado por fuera de ésta.
Definition at line 46 of file queue.c.
References list_add().