My Project: src/commons/string.h File Reference
string.h File Reference
#include <commons/string.h>
#include <stdbool.h>
#include <stdarg.h>
Functions
char * string_new (void)
Crea un string vacio.
char * string_itoa (int number)
Crea un string en formato decimal a partir de un número.
char * string_from_format (const char *format,...) __attribute__((format(printf
Crea un nuevo string a partir de un formato especificado.
char char * string_from_vformat (const char *format, va_list arguments)
Crea un nuevo string a partir de un formato especificado pasando un va_list con los argumentos.
char * string_repeat (char ch, int count)
Crea un string de longitud count con el mismo caracter.
void string_append (char **original, char *string_to_add)
Agrega al primer string el segundo.
void string_n_append (char **original, char *string_to_add, int n)
Agrega al primer string un máximo de n caracteres del segundo.
void string_append_with_format (char **original, const char *format,...) __attribute__((format(printf
Concatena al primer string el resultado de aplicar los parametros al formato especificado.
void char * string_duplicate (char *original)
Retorna una copia del string pasado como argumento.
void string_to_upper (char *text)
Pone en mayuscula todos los caracteres de un string.
void string_to_lower (char *text)
Pone en minuscula todos los caracteres de un string.
void string_capitalized (char *text)
Capitaliza un string.
void string_trim (char **text)
Remueve todos los caracteres vacios de la derecha y la izquierda.
void string_trim_left (char **text)
Remueve todos los caracteres vacios de la izquierda.
void string_trim_right (char **text)
Remueve todos los caracteres vacios de la derecha.
int string_length (char *text)
Retorna la longitud del string.
bool string_is_empty (char *text)
Retorna si un string es "".
bool string_starts_with (char *text, char *begin)
Retorna un boolean que indica si el string text comienza con el string begin pasado por parametro.
bool string_ends_with (char *text, char *end)
Retorna un boolean que indica si el string text finaliza con el string end pasado por parametro.
bool string_equals_ignore_case (char *actual, char *expected)
Retorna si dos strings son iguales ignorando las mayusculas y minusculas.
char ** string_split (char *text, char *separator)
Separa un string dado un separador.
char ** string_n_split (char *text, int n, char *separator)
Separa un string tantas veces por su separador como n lo permita.
char * string_substring (char *text, int start, int length)
Retorna los length caracteres de text empezando en start en un nuevo string.
char * string_substring_from (char *text, int start)
Retorna el substring de text desde el indice start hasta el último de la palabra.
char * string_substring_until (char *text, int length)
Retorna los primeros length caracteres de text como un nuevo string.
void string_iterate_lines (char **strings, void(*closure)(char *))
Itera un array de strings y aplica la función closure a cada uno.
char ** string_get_string_as_array (char *text)
Retorna un array de strings a partir de un string formateado como array.
char * string_reverse (char *text)
Retorna el texto invertido. No se maneja el caso de NULL, si se pasa NULL su comportamiento no esta determinado.
char * string_replace (char *text, char *substring, char *replacement)
Retorna una copia de un string con todas las ocurrencias de un substring no vacío siendo reemplazadas por otro string.
bool string_contains (char *text, char *substring)
Retorna un boolean que indica si text contiene o no a substring.
char ** string_array_new (void)
Crea un array de strings vacio.
void string_array_destroy (char **array)
Destruye un array con sus strings.
int string_array_size (char **array)
Retorna la cantidad de líneas del array de strings.
bool string_array_is_empty (char **array)
Verifica si el array de strings está vacío.
void string_array_push (char ***array, char *text)
Agrega un string al final del array.
char * string_array_replace (char **array, int pos, char *text)
Reemplaza un string en un array por otro.
char * string_array_pop (char **array)
Quita el último string del array y lo retorna.
Detailed Description
#include <commons/string.h>
Definition in file string.h.
Function Documentation
string_append()
void string_append (char ** original, char * string_to_add)
Agrega al primer string el segundo.
Parameters
[in,out] original Puntero al string al que se le va a concatenar el segundo. Debe apuntar a un puntero liberable con free()
[in] string_to_add String a concatenar. Admite todo tipo de strings
char *unaPalabra = string_new();
string_append(&unaPalabra, "HOLA ");
string_append(&unaPalabra, "PEPE");
=> unaPalabra = "HOLA PEPE"
Definition at line 46 of file string.c.
string_append_with_format()
void string_append_with_format (char ** original, const char * format, ...)
Concatena al primer string el resultado de aplicar los parametros al formato especificado.
Parameters
[in,out] original Puntero al string a modificar. Debe apuntar a un string liberable con free()
[in] format Formato a aplicar, igual que en printf()
char *saludo = "HOLA ";
char *nombre = "PEPE";
string_append_with_format(&saludo, "%s!", nombre);
=> saludo = "HOLA PEPE!"
string_array_destroy()
void string_array_destroy (char ** array)
Destruye un array con sus strings.
Parameters
[in,out] array Puntero al array a destruir. Debe apuntar a un array de strings liberables con free() y terminado en NULL
Definition at line 249 of file string.c.
References string_iterate_lines().
string_array_is_empty()
bool string_array_is_empty (char ** array)
Verifica si el array de strings está vacío.
Parameters
[in] array Array de strings terminado en NULL
Definition at line 264 of file string.c.
string_array_new()
char** string_array_new (void)
Crea un array de strings vacio.
Returns
El array retornado debe ser liberado con string_array_destroy()
Definition at line 242 of file string.c.
string_array_pop()
char* string_array_pop (char ** array)
Quita el último string del array y lo retorna.
Parameters
[in,out] array Array a modificar. Debe apuntar a un array de strings terminado en NULL
Returns
El string quitado. Deja de pertenecer al array, por lo que debe ser liberado con free()
Definition at line 279 of file string.c.
References string_array_replace(), and string_array_size().
string_array_push()
void string_array_push (char *** array, char * text)
Agrega un string al final del array.
Parameters
[in,out] array Puntero al array a modificar. Debe apuntar a un array de strings modificable y terminado en NULL
[in] text String a agregar. Debe ser liberable con free(), pero pasa a formar parte del array, por lo que no debe ser liberado
char** array = string_array_new(); => {NULL}
string_array_push(&array, "hola"); => {"hola", NULL}
string_array_push(&array, "mundo"); => {"hola", "mundo", NULL}
Definition at line 268 of file string.c.
References string_array_size().
string_array_replace()
char* string_array_replace (char ** array, int pos, char * text)
Reemplaza un string en un array por otro.
Parameters
[in,out] array Array a modificar. Debe apuntar a un array de strings terminado en NULL
[in] pos Posición del string a reemplazar
[in] text Nuevo string a insertar. Debe ser liberable con free(), pero pasa a formar parte del array, por lo que no debe ser liberado
Returns
El string reemplazado. Debe ser liberado con free()
Definition at line 272 of file string.c.
string_array_size()
int string_array_size (char ** array)
Retorna la cantidad de líneas del array de strings.
Parameters
[in] array Array de strings terminado en NULL
Definition at line 254 of file string.c.
References string_iterate_lines().
string_capitalized()
void string_capitalized (char * text)
Capitaliza un string.
Parameters
[in,out] text String a modificar. Debe apuntar a cualquier porción de memoria modificable (en el stack o en el heap)
char* heap_string = string_duplicate("hola");
string_capitalized(heap_string); => "Hola"
char[] stack_string = "hola";
string_capitalized(stack_string); => "Hola"
char* literal_string = "hola";
string_capitalized(literal_string); => Error!
Definition at line 97 of file string.c.
References string_is_empty(), and string_to_lower().
string_contains()
bool string_contains (char * text, char * substring)
Retorna un boolean que indica si text contiene o no a substring.
Parameters
[in] text String a evaluar. Admite todo tipo de strings
[in] substring Substring a buscar. Admite todo tipo de strings
Definition at line 238 of file string.c.
string_duplicate()
void char* string_duplicate (char * original)
Retorna una copia del string pasado como argumento.
Parameters
[in] original String a duplicar. Admite todo tipo de strings
Returns
El string retornado debe ser liberado con free()
char* copia = string_duplicate("hola");
Definition at line 42 of file string.c.
string_ends_with()
bool string_ends_with (char * text, char * end)
Retorna un boolean que indica si el string text finaliza con el string end pasado por parametro.
Parameters
[in] text String a evaluar. Admite todo tipo de strings
[in] end String a buscar. Admite todo tipo de strings
string_ends_with("hola mundo", "mundo") => true
string_ends_with("mundo", "hola mundo") => false
Definition at line 142 of file string.c.
string_equals_ignore_case()
bool string_equals_ignore_case (char * actual, char * expected)
Retorna si dos strings son iguales ignorando las mayusculas y minusculas.
Parameters
[in] actual String a comparar. Admite todo tipo de strings
[in] expected String a comparar. Admite todo tipo de strings
string_equals_ignore_case("hola", "hola") => true
string_equals_ignore_case("hola", "HOLA") => true
string_equals_ignore_case("hola", "mundo") => false
Definition at line 151 of file string.c.
string_from_format()
char* string_from_format (const char * format, ...)
Crea un nuevo string a partir de un formato especificado.
Parameters
[in] format Formato a aplicar, igual que en printf()
Returns
El string retornado debe ser liberado con free()
char* saludo = string_from_format("Hola %s", "mundo");
=> saludo = "Hola mundo"
string_from_vformat()
char char* string_from_vformat (const char * format, va_list arguments)
Crea un nuevo string a partir de un formato especificado pasando un va_list con los argumentos.
Parameters
[in] format Formato a aplicar, igual que en vprintf()
[in] arguments Lista de argumentos a aplicar, igual que en vprintf()
Returns
Retorna un string que debe ser liberado con free()
Definition at line 72 of file string.c.
References string_new().
string_get_string_as_array()
char** string_get_string_as_array (char * text)
Retorna un array de strings a partir de un string formateado como array.
Parameters
[in] text String a convertir. Admite todo tipo de strings
Returns
Retorna un array de copias de los caracteres en text y en la última posición un NULL. Debe ser liberado con string_array_destroy()
char* array_string = "[1,2,3,4]"
string_get_value_as_array(array_string) => {"1", "2", "3", "4", NULL}
Definition at line 169 of file string.c.
References string_split(), string_substring(), and string_trim().
string_is_empty()
bool string_is_empty (char * text)
Retorna si un string es "".
Parameters
[in] text String a evaluar. Admite todo tipo de strings
string_is_empty("hola") => false
string_is_empty("") => true
Definition at line 134 of file string.c.
string_iterate_lines()
void string_iterate_lines (char ** strings, void(*)(char *) closure)
Itera un array de strings y aplica la función closure a cada uno.
Parameters
[in] strings Array de strings a iterar
[in] closure Función a aplicar a cada string
Definition at line 198 of file string.c.
string_itoa()
char* string_itoa (int number)
Crea un string en formato decimal a partir de un número.
Parameters
[in] number Número entero a convertir
Returns
El string retornado debe ser liberado con free()
char* numero = string_itoa(123);
=> numero = "123"
Definition at line 78 of file string.c.
References string_from_format().
string_length()
int string_length (char * text)
Retorna la longitud del string.
Parameters
[in] text String a medir. Admite todo tipo de strings
string_length("hola") => 4
Definition at line 205 of file string.c.
string_n_append()
void string_n_append (char ** original, char * string_to_add, int n)
Agrega al primer string un máximo de n caracteres del segundo.
Parameters
[in,out] original Puntero al string a modificar. Debe apuntar a un string liberable con free()
[in] string_to_add String a concatenar. Admite todo tipo de strings
[in] n Cantidad máxima de caracteres a concatenar
char *unaPalabra = string_new();
string_n_append(&unaPalabra, "HOLA ", 10);
string_n_append(&unaPalabra, "PEPE", 3);
=> unaPalabra = "HOLA PEP"
Definition at line 51 of file string.c.
string_n_split()
char** string_n_split (char * text, int n, char * separator)
Separa un string tantas veces por su separador como n lo permita.
Parameters
[in] text String a separar. Admite todo tipo de strings
[in] n Cantidad máxima de veces que se puede separar
[in] separator String separador a utilizar. Admite todo tipo de strings
Returns
Retorna un array de copias de los caracteres en text y en la última posición un NULL. Debe ser liberado con string_array_destroy()
string_n_split("hola, mundo, bueno", 2, ",") => ["hola", " mundo, bueno", NULL]
string_n_split("hola, mundo, bueno", 3, ",") => ["hola", " mundo", " bueno", NULL]
string_n_split("hola, mundo, bueno", 10, ",") => ["hola", " mundo", " bueno", NULL]
Definition at line 162 of file string.c.
string_new()
char* string_new (void)
Crea un string vacio.
Returns
El string retornado debe ser liberado con free()
Definition at line 59 of file string.c.
References string_duplicate().
string_repeat()
char* string_repeat (char ch, int count)
Crea un string de longitud count con el mismo caracter.
Parameters
[in] ch Caracter a repetir
[in] count Cantidad de veces a repetir el caracter
Returns
El string retornado debe ser liberado con free()
string_repeat('a', 5) = "aaaaa"
Definition at line 33 of file string.c.
string_replace()
char* string_replace (char * text, char * substring, char * replacement)
Retorna una copia de un string con todas las ocurrencias de un substring no vacío siendo reemplazadas por otro string.
Parameters
[in] text String a modificar. Admite todo tipo de strings
[in] substring Substring a reemplazar. Admite todo tipo de strings
[in] replacement String a insertar. Admite todo tipo de strings
Returns
Retorna un nuevo string que debe ser liberado con free()
char* original = "hello";
string_replace(original, "ello", "ola") => "hola"
string_replace(original, "l", ""); => "heo"
string_replace(original, "not a substring", "yay!"); => "hello"
Definition at line 222 of file string.c.
References string_append(), string_length(), string_n_append(), and string_new().
string_reverse()
char* string_reverse (char * text)
Retorna el texto invertido. No se maneja el caso de NULL, si se pasa NULL su comportamiento no esta determinado.
Parameters
[in] text String a invertir. Admite todo tipo de strings
Returns
Retorna un nuevo string que debe ser liberado con free()
char* original = "boo";
string_reverse(original) => "oob"
Definition at line 209 of file string.c.
References string_length().
string_split()
char** string_split (char * text, char * separator)
Separa un string dado un separador.
Parameters
[in] text String a separar. Admite todo tipo de strings
[in] separator Separador a utilizar. Admite todo tipo de strings
Returns
Retorna un array con cada palabra y en la última posición un NULL. Debe ser liberado con string_array_destroy()
string_split("hola, mundo", ",") => {"hola", " mundo", NULL}
Definition at line 155 of file string.c.
string_starts_with()
bool string_starts_with (char * text, char * begin)
Retorna un boolean que indica si el string text comienza con el string begin pasado por parametro.
Parameters
[in] text String a evaluar. Admite todo tipo de strings
[in] begin String a buscar. Admite todo tipo de strings
string_starts_with("hola mundo", "hola") => true
string_starts_with("hola", "hola mundo") => false
Definition at line 138 of file string.c.
string_substring()
char* string_substring (char * text, int start, int length)
Retorna los length caracteres de text empezando en start en un nuevo string.
Parameters
[in] text String a partir del cual se obtiene el substring. Admite todo tipo de strings
[in] start Indice desde el cual se obtiene el substring
[in] length Cantidad de caracteres a obtener
Returns
Retorna un nuevo string que debe ser liberado con free()
string_substring("hola, mundo, bueno", 0, 4) => "hola"
string_substring("hola, mundo, bueno", 7, 5) => "mundo"
string_n_split("hola, mundo, bueno", 1, 3) => "ola"
Definition at line 184 of file string.c.
string_substring_from()
char* string_substring_from (char * text, int start)
Retorna el substring de text desde el indice start hasta el último de la palabra.
Parameters
[in] text String a partir del cual se obtiene el substring. Admite todo tipo de strings
[in] start Indice desde el cual se obtiene el substring
Returns
Retorna un nuevo string que debe ser liberado con free()
Definition at line 190 of file string.c.
References string_substring().
string_substring_until()
char* string_substring_until (char * text, int length)
Retorna los primeros length caracteres de text como un nuevo string.
Parameters
[in] text String a partir del cual se obtiene el substring. Admite todo tipo de strings
[in] length Cantidad de caracteres a obtener
Returns
Retorna un nuevo string que debe ser liberado con free()
Definition at line 194 of file string.c.
References string_substring().
string_to_lower()
void string_to_lower (char * text)
Pone en minuscula todos los caracteres de un string.
Parameters
[in,out] text String a modificar. Debe apuntar a cualquier porción de memoria modificable (en el stack o en el heap)
char* heap_string = string_duplicate("HOLA");
string_to_lower(heap_string); => "hola"
char[] stack_string = "HOLA";
string_to_lower(stack_string); => "hola"
char* literal_string = "HOLA";
string_to_lower(literal_string); => Error!
Definition at line 93 of file string.c.
string_to_upper()
void string_to_upper (char * text)
Pone en mayuscula todos los caracteres de un string.
Parameters
[in,out] text String a modificar. Debe apuntar a cualquier porción de memoria modificable (en el stack o en el heap)
char* heap_string = string_duplicate("hola");
string_to_upper(heap_string); => "HOLA"
char[] stack_string = "hola";
string_to_upper(stack_string); => "HOLA"
char* literal_string = "hola";
string_to_upper(literal_string); => Error!
Definition at line 89 of file string.c.
string_trim()
void string_trim (char ** text)
Remueve todos los caracteres vacios de la derecha y la izquierda.
Parameters
[in,out] text Puntero al string a modificar. Debe apuntar a un string liberable con free()
char* heap_string = string_duplicate("  hola  ");
string_trim(&heap_string); => "hola"
char[] stack_string = "  mundo  ";
string_trim(&stack_string); => Error!
Definition at line 106 of file string.c.
References string_trim_left(), and string_trim_right().
string_trim_left()
void string_trim_left (char ** text)
Remueve todos los caracteres vacios de la izquierda.
Parameters
[in,out] text Puntero al string a modificar. Debe apuntar a un string liberable con free()
char* heap_string = string_duplicate("  hola");
string_trim_left(&heap_string); => "hola"
char[] stack_string = "  mundo";
string_trim_left(&stack_string); => Error!
Definition at line 111 of file string.c.
References string_duplicate().
string_trim_right()
void string_trim_right (char ** text)
Remueve todos los caracteres vacios de la derecha.
Parameters
[in,out] text Puntero al string a modificar. Debe apuntar a un string liberable con free()
char* heap_string = string_duplicate("hola  ");
string_trim_right(&heap_string); => "hola"
char[] stack_string = "mundo  ";
string_trim_right(&stack_string); => Error!
Definition at line 124 of file string.c.