My Project: src/commons/temporal.h File Reference
temporal.h File Reference
#include <commons/temporal.h>
#include <stdint.h>
#include <time.h>
Data Structures
struct t_temporal
Manejo de tiempo con cronómetro. Inicializar con temporal_create().
Enumerations
enum t_temporal_status { TEMPORAL_STATUS_STOPPED, TEMPORAL_STATUS_RUNNING }
Functions
char * temporal_get_string_time (const char *format)
Retorna un string con la hora actual con el formato recibido por parámetro.
t_temporal * temporal_create (void)
Crea una variable temporal e inicia su cronómetro.
void temporal_destroy (t_temporal *temporal)
Destruye una variable temporal.
int64_t temporal_gettime (t_temporal *temporal)
Retorna el tiempo total transcurrido mientras el cronómetro estuvo activo en milisegundos.
void temporal_stop (t_temporal *temporal)
Detiene el cronómetro de una variable temporal.
void temporal_resume (t_temporal *temporal)
Reanuda el cronómetro de una variable temporal.
int64_t temporal_diff (t_temporal *temporal_1, t_temporal *temporal_2)
Retorna la diferencia del tiempo total transcurrido entre dos variables temporales en milisegundos.
Detailed Description
#include <commons/temporal.h>
Definition in file temporal.h.
Enumeration Type Documentation
t_temporal_status
enum t_temporal_status
Estado del cronómetro
Enumerator
TEMPORAL_STATUS_STOPPED
Cronómetro detenido.
TEMPORAL_STATUS_RUNNING
Cronómetro en marcha.
Definition at line 30 of file temporal.h.
Function Documentation
temporal_create()
t_temporal* temporal_create (void)
Crea una variable temporal e inicia su cronómetro.
Returns
La variable temporal creada debe ser liberada con temporal_destroy().
Definition at line 52 of file temporal.c.
References error_show(), and TEMPORAL_STATUS_RUNNING.
temporal_destroy()
void temporal_destroy (t_temporal * temporal)
Destruye una variable temporal.
Parameters
temporal Variable temporal a destruir.
Definition at line 67 of file temporal.c.
temporal_diff()
int64_t temporal_diff (t_temporal * temporal_1, t_temporal * temporal_2)
Retorna la diferencia del tiempo total transcurrido entre dos variables temporales en milisegundos.
Parameters
temporal_1 Primera variable temporal.
temporal_2 Segunda variable temporal.
Definition at line 102 of file temporal.c.
References temporal_gettime().
temporal_get_string_time()
char* temporal_get_string_time (const char * format)
Retorna un string con la hora actual con el formato recibido por parámetro.
Returns
El string retornado debe ser liberado con free() al dejar de usarse.
temporal_get_string_time("%d/%m/%y") => "30/09/20"
temporal_get_string_time("%H:%M:%S:%MS") => "12:51:59:331"
temporal_get_string_time("%d/%m/%y %H:%M:%S") => "30/09/20 12:51:59"
Definition at line 26 of file temporal.c.
References error_show(), and string_from_format().
temporal_gettime()
int64_t temporal_gettime (t_temporal * temporal)
Retorna el tiempo total transcurrido mientras el cronómetro estuvo activo en milisegundos.
Parameters
temporal Variable temporal.
Definition at line 71 of file temporal.c.
References TEMPORAL_STATUS_STOPPED.
temporal_resume()
void temporal_resume (t_temporal * temporal)
Reanuda el cronómetro de una variable temporal.
Parameters
temporal Variable temporal a reanudar.
Definition at line 90 of file temporal.c.
References error_show(), and TEMPORAL_STATUS_RUNNING.
temporal_stop()
void temporal_stop (t_temporal * temporal)
Detiene el cronómetro de una variable temporal.
Parameters
temporal Variable temporal a frenar.
Definition at line 81 of file temporal.c.
References TEMPORAL_STATUS_STOPPED.